### PR TITLE
fix uikit build in sync androidx 1.2.1

### PR DESCRIPTION
**Pull request by dima-avdeev-jb**
On uikit fails this code:
```Kotlin
var textState1 by remember { mutableStateOf("text field 1") }
```
But work's this:
```Kotlin
val textState1 = remember { mutableStateOf("text field 1") }
```

### CODE REVIEW

**Review by igordmn — APPROVED** [review]

**Review by eymar — APPROVED** [review]
What's the error when "by" is used?

**Comment by dima-avdeev-jb** [comment]
> What's the error when "by" is used?

Failed with this error:
```
Compilation failed: no function <set-textState1> in androidx.compose.mpp.demo
```

**Comment by igordmn** [comment]
CI is failing, so I think no one will mind if I merge this PR :)
